################################# Default configuration ###################
baseURL = "https://uniproyect.com"
title = "UniProyect"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
defaultContentLanguage = "es" # used for file names
#defaultContentLanguageInSubdir = true
disableLanguages = ["en"]

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation Español ##################################
[[menu.main]]
name = "Sobre Nosotros"
URL = "about"
weight = 1

[[menu.main]]
name = "Servicios"
URL = "services"
weight = 2

#[[menu.main]]
#name = "Portfolio"
#URL = "portfolio"
#weight = 3

[[menu.main]]
name = "Equipo"
URL = "team"
weight = 4

#[[menu.main]]
#name = "Precio"
#URL = "pricing"
#weight = 5

#[[menu.main]]
#name = "Blog"
#URL = "blog"
#weight = 6

[[menu.main]]
name = "Contacto"
URL = "contact"
weight = 7

############################# Default Parameters ##########################
[params]
logo = "images/logo-letras.png"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Themefisher"
# Google Analitycs
google_analitycs_id = "UA-163324892-1" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
#link = "#"
#
#[[params.social]]
#icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
#link = "#"

################################ Spanish Language ########################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 1
home = "Inicio"

################################ Catalan Language ########################
[Languages.ca]
languageName = "Ca"
languageCode = "ca"
contentDir = "content/catala"
weight = 2
home = "Inici"

############################# Navigation Catalan ##################################
[[Languages.ca.menu.main]]
name = "Sobre Nosaltres"
URL = "about"
weight = 1

[[Languages.ca.menu.main]]
name = "Serveis"
URL = "services"
weight = 2

#[[Languages.ca.menu.main]]
#name = "Portfolio"
#URL = "portfolio"
#weight = 3

[[Languages.ca.menu.main]]
name = "Equip"
URL = "team"
weight = 4

#[[Languages.ca.menu.main]]
#name = "Precio"
#URL = "pricing"
#weight = 5

#[[Languages.ca.menu.main]]
#name = "Blog"
#URL = "blog"
#weight = 6

[[Languages.ca.menu.main]]
name = "Contacte"
URL = "contact"
weight = 7

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 3
home = "Home"
